#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling and testing your project before committing'
# Check ESLint Standards
npx lint-staged ||
    (
        echo '❌ ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false
    )

# Check tsconfig standards
npm run check-types ||
    (
        echo '❌ Failed Type check. Check your typescript types.'
        false
    )

# If everything passes... Now we can commit
echo '✅ All checks passed.'

# If everything passes... Now we can commit
echo '✏ Commiting your changes.'

