#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling and testing your project before committing'
npx lint-staged ||
    (
        echo '❌ ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false
    )

echo '✅ All checks passed.'
echo '✏ Commiting your changes.'